sudo: required
dist: bionic
addons:
  chrome: stable

language: node_js

node_js:
  - 10.13.0

script:
  - npm test --silent

notifications:
  webhooks:
    - https://learn.javascript.ru/taskbook/travis/notifications
